//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSP
    {
        public int id { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaColor { get; set; }
        public Nullable<int> MaCapacity { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Capacity Capacity { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual Color Color { get; set; }
    }
}
