//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int id { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ChiTietGH ChiTietGH { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
