//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDBAN()
        {
            this.CHITIETHDBANs = new HashSet<CHITIETHDBAN>();
        }
    
        public string MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public string TrangThaiTT { get; set; }
        public string TrangThaiDH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<bool> New { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
