//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SANPHAM
    {
        DB_DiDongEntities database = new DB_DiDongEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHDBANs = new HashSet<CHITIETHDBAN>();
            this.ChiTietSPs = new HashSet<ChiTietSP>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public string Hinh { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSP> ChiTietSPs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public decimal GiaMacDinh(int id)
        {
            return (decimal)database.ChiTietSPs.Where(n => n.MaSP == id).FirstOrDefault().Gia;
        }
    }
}
